manifest:
  version: "0.13"
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: c64cf28f71f362e9c5efa389567f54a386e802dc
      west-commands: scripts/west-commands.yml
    - name: cmsis
      path: modules/hal/cmsis
      url: https://github.com/zephyrproject-rtos/cmsis
      revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
    - name: cmsis_6
      path: modules/hal/cmsis_6
      url: https://github.com/zephyrproject-rtos/CMSIS_6
      revision: b2dfbe1a20bbd49c2d2c605073799671074bbb30
    - name: hal_bestechnic
      path: modules/hal/bestechnic
      url: https://github.com/zhxt/hal_bestechnic.git
      revision: 7e00feff5350c5b35b29660b28965be8b8bde607
  self:
    path: bestechnic-zephyr
